site_name: realestate-rag-mcp
repo_url: https://github.com/danny-tdoan/realestate-rag-mcp
site_url: https://danny-tdoan.github.io/realestate-rag-mcp
site_description: MCP server containing tools for real esate search
site_author: Danny Doan
edit_uri: edit/main/docs/
repo_name: danny-tdoan/realestate-rag-mcp
copyright: Maintained by <a href="https://danny-tdoan.com">danny-tdoan</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["realestate_rag_mcp"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danny-tdoan/realestate-rag-mcp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/realestate-rag-mcp

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
